TORCHVISION_MODEL_CATALOG = {
    "mobilenetv2": ["mobilenet_v2"],
    "mobilenetv3": ["mobilenet_v3_large", "mobilenet_v3_small"],
    "resnet": ["resnet18", "resnet34", "resnet50", "resnet101", "resnet152"],
    "resnext": ["resnext50_32x4d", "resnext101_32x8d"],
    "regnet": ["regnet_y_400mf", "regnet_y_800mf", "regnet_y_1_6gf", "regnet_y_3_2gf"],
    "resnest": ["resnest50", "resnest101", "resnest200", "resnest269"],
    "regnest": ["regnest200", "regnest269"],
    "efficientnet": ["efficientnet_b0", "efficientnet_b1", "efficientnet_b2", "efficientnet_b3", "efficientnet_b4", "efficientnet_b5", "efficientnet_b6", "efficientnet_b7"],
    "efficientnetv2": ["efficientnet_v2_s", "efficientnet_v2_m", "efficientnet_v2_l"],
    "repvgg": ["repvgg_a0", "repvgg_a1", "repvgg_a2", "repvgg_b0", "repvgg_b1", "repvgg_b2", "repvgg_b3"],
    "nfnet": ["nfnet_f0", "nfnet_f1", "nfnet_f2", "nfnet_f3", "nfnet_f4", "nfnet_f5", "nfnet_f6", "nfnet_f7"],
    "convnext": ["convnext_tiny", "convnext_small", "convnext_base", "convnext_large"],
    "convnextv2": ["convnextv2_tiny", "convnextv2_small", "convnextv2_base", "convnextv2_large"],
    "relknet": ["relknet_200", "relknet_300", "relknet_400", "relknet_500"],
    "hgnetv2": ["hgnetv2_tiny", "hgnetv2_small", "hgnetv2_base", "hgnetv2_large"]
}

['ConvNeXt', 'EfficientNet', 'MobileNetV2', 'MobileNetV3', 'RegNet', 'ResNet', 'ShuffleNetV2', 'SqueezeNet', 'SwinTransformer', 'VGG', 'VisionTransformer', 'alexnet', 'convnext', 'convnext_base', 'convnext_large', 'convnext_small', 'convnext_tiny', 'densenet', 'densenet121', 'densenet161', 'densenet169', 'densenet201', 'detection', 'efficientnet', 'efficientnet_b0', 'efficientnet_b1', 'efficientnet_b2', 'efficientnet_b3', 'efficientnet_b4', 'efficientnet_b5', 'efficientnet_b6', 'efficientnet_b7', 'efficientnet_v2_l', 'efficientnet_v2_m', 'efficientnet_v2_s', 'get_model', 'get_model_builder', 'get_weight', 'googlenet', 'inception', 'inception_v3', 'list_models', 'maxvit', 'maxvit_t', 'mnasnet', 'mnasnet0_5', 'mnasnet0_75', 'mnasnet1_0', 'mnasnet1_3', 'mobilenet', 'mobilenet_v2', 'mobilenet_v3_large', 'mobilenet_v3_small', 'mobilenetv2', 'mobilenetv3', 'optical_flow', 'quantization', 'regnet', 'regnet_x_16gf', 'regnet_x_1_6gf', 'regnet_x_32gf', 'regnet_x_3_2gf', 'regnet_x_400mf', 'regnet_x_800mf', 'regnet_x_8gf', 'regnet_y_128gf', 'regnet_y_16gf', 'regnet_y_1_6gf', 'regnet_y_32gf', 'regnet_y_3_2gf', 'regnet_y_400mf', 'regnet_y_800mf', 'regnet_y_8gf', 'resnet', 'resnet101', 'resnet152', 'resnet18', 'resnet34', 'resnet50', 'resnext101_32x8d', 'resnext101_64x4d', 'resnext50_32x4d', 'segmentation', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'shufflenetv2', 'squeezenet', 'squeezenet1_0', 'squeezenet1_1', 'swin_b', 'swin_s', 'swin_t', 'swin_transformer', 'swin_v2_b', 'swin_v2_s', 'swin_v2_t', 'vgg', 'vgg11', 'vgg11_bn', 'vgg13', 'vgg13_bn', 'vgg16', 'vgg16_bn', 'vgg19', 'vgg19_bn', 'video', 'vision_transformer', 'vit_b_16', 'vit_b_32', 'vit_h_14', 'vit_l_16','vit_l_32', 'wide_resnet101_2', 'wide_resnet50_2']

# (model_name, weights, transforms)
CATALOG = {

    ('mobilenet_v2', '.MobileNet_V2_Weights.DEFAULT', 'MobileNet_V2_Weights.IMAGENET1K_V1.transforms'),
    ('mobilenet_v3_small', '.MobileNet_V3_Small_Weights.DEFAULT', 'MobileNet_V3_Small_Weights.IMAGENET1K_V1.transforms'),
    ('mobilenet_v3_large', '.MobileNet_V3_Large_Weights.DEFAULT', 'MobileNet_V3_Large_Weights.IMAGENET1K_V1.transforms'),
    ('convnext_tiny', 'ConvNeXt_Tiny_Weights.DEFAULT', 'ConvNeXt_Tiny_Weights.IMAGENET1K_V1.transforms'),
    ('convnext_small', 'ConvNeXt_Small_Weights.DEFAULT', 'ConvNeXt_Small_Weights.IMAGENET1K_V1.transforms'),
    ('convnext_base', 'ConvNeXt_Base_Weights.DEFAULT', 'ConvNeXt_Base_Weights.IMAGENET1K_V1.transforms'),
    ('convnext_large', 'ConvNeXt_Large_Weights.DEFAULT', 'ConvNeXt_Large_Weights.IMAGENET1K_V1.transforms'), 
    ('regnet_y_400mf', 'RegNet_Y_400MF_Weights.DEFAULT', 'RegNet_Y_400MF_Weights.IMAGENET1K_V2.transforms'),
    ('regnet_y_800mf', 'RegNet_Y_800MF_Weights.DEFAULT', 'RegNet_Y_800MF_Weights.IMAGENET1K_V2.transforms'),
    ('regnet_y_1_6gf', 'RegNet_Y_1_6GF_Weights.DEFAULT', 'RegNet_Y_1_6GF_Weights.IMAGENET1K_V2.transforms'),
    ('regnet_y_3_2gf', 'RegNet_Y_3_2GF_Weights.DEFAULT', 'RegNet_Y_3_2GF_Weights.IMAGENET1K_V2.transforms'),
    ('regnet_x_400mf', 'RegNet_X_400MF_Weights.DEFAULT', 'RegNet_X_400MF_Weights.IMAGENET1K_V2.transforms'),
    ('regnet_x_800mf', 'RegNet_X_800MF_Weights.DEFAULT', 'RegNet_X_800MF_Weights.IMAGENET1K_V2.transforms'),
    ('regnet_x_1_6gf', 'RegNet_X_1_6GF_Weights.DEFAULT', 'RegNet_X_1_6GF_Weights.IMAGENET1K_V2.transforms'),
    ('regnet_x_3_2gf', 'RegNet_X_3_2GF_Weights.DEFAULT', 'RegNet_X_3_2GF_Weights.IMAGENET1K_V2.transforms'),
    # There are more regnets...
    ('', '', ''),
    ('', '', ''),
    ('', '', ''),
    ('', '', ''),
    ('', '', ''),
    ('', '', ''),
    ('', '', ''),
    ('', '', ''),
    ('', '', ''),

}
# TORCHVISION_WEIGHTS_CATALOG = {
#     "mobilenet_v2": tv_weights.MobileNet_V2_Weights.DEFAULT,
#     "mobilenet_v3_large": tv_weights.MobileNet_V3_Large_Weights.DEFAULT,
#     "mobilenet_v3_small": tv_weights.MobileNet_V3_Small_Weights.DEFAULT,
#     "resnet18": tv_weights.ResNet18_Weights.DEFAULT,
#     "resnet34": tv_weights.ResNet32_Weights.DEFAULT,
#     "resnet50": tv_weights.ResNet50_Weights.DEFAULT,
#     "resnet101": tv_weights.ResNet101_Weights.DEFAULT,
#     "resnet152": tv_weights.ResNet152_Weights.DEFAULT,
#     "resnext50_32x4d": tv_weights.ResNeXt50_32x4d_Weights.DEFAULT,
#     "resnext101_32x8d": tv_weights.ResNeXt101_32x8d_Weights.DEFAULT,
#     "regnet_y_400mf": tv_weights.RegNet_Y_400MF_Weights.DEFAULT,
#     "regnet_y_800mf": tv_weights.RegNet_Y_800MF_Weights.DEFAULT,
#     "regnet_y_1_6gf": tv_weights.RegNet_Y_1_6GF_Weights.DEFAULT,
#     "regnet_y_3_2gf": tv_weights.RegNet_Y_3_2GF_Weights.DEFAULT,
#     "resnest50": tv_weights.ResNeSt50_Weights.DEFAULT,
#     "resnest101": tv_weights.ResNeSt101_Weights.DEFAULT,
#     "resnest200": tv_weights.ResNeSt200_Weights.DEFAULT,
#     "resnest269": tv_weights.ResNeSt269_Weights.DEFAULT,
#     "regnest200": tv_weights.RegNeSt200_Weights.DEFAULT,
#     "regnest269": tv_weights.RegNeSt269_Weights.DEFAULT,
#     "efficientnet_b0": tv_weights.EfficientNet_B0_Weights.DEFAULT,
#     "efficientnet_b1": tv_weights.EfficientNet_B1_Weights.DEFAULT,
#     "efficientnet_b2": tv_weights.EfficientNet_B2_Weights.DEFAULT,
#     "efficientnet_b3": tv_weights.EfficientNet_B3_Weights.DEFAULT,
#     "efficientnet_b4": tv_weights.EfficientNet_B4_Weights.DEFAULT,
#     "efficientnet_b5": tv_weights.EfficientNet_B5_Weights.DEFAULT,
#     "efficientnet_b6": tv_weights.EfficientNet_B6_Weights.DEFAULT,
#     "efficientnet_b7": tv_weights.EfficientNet_B7_Weights.DEFAULT,
#     "efficientnet_v2_s": tv_weights.EfficientNet_V2_S_Weights.DEFAULT,
#     "efficientnet_v2_m": tv_weights.EfficientNet_V2_M_Weights.DEFAULT,
#     "efficientnet_v2_l": tv_weights.EfficientNet_V2_L_Weights.DEFAULT,
#     "repvgg_a0": tv_weights.RepVGG_A0_Weights.DEFAULT,
#     "repvgg_a1": tv_weights.RepVGG_A1_Weights.DEFAULT,
#     "repvgg_a2": tv_weights.RepVGG_A2_Weights.DEFAULT,
#     "repvgg_b0": tv_weights.RepVGG_B0_Weights.DEFAULT,
#     "repvgg_b1": tv_weights.RepVGG_B1_Weights.DEFAULT,
#     "repvgg_b2": tv_weights.RepVGG_B2_Weights.DEFAULT,
#     "repvgg_b3": tv_weights.RepVGG_B3_Weights.DEFAULT,
#     "nfnet_f0": tv_weights.NFNet_F0_Weights.DEFAULT,
#     "nfnet_f1": tv_weights.NFNet_F1_Weights.DEFAULT,
#     "nfnet_f2": tv_weights.NFNet_F2_Weights.DEFAULT,
#     "nfnet_f3": tv_weights.NFNet_F3_Weights.DEFAULT,
#     "nfnet_f4": tv_weights.NFNet_F4_Weights.DEFAULT,
#     "nfnet_f5": tv_weights.NFNet_F5_Weights.DEFAULT,
#     "nfnet_f6": tv_weights.NFNet_F6_Weights.DEFAULT,
#     "nfnet_f7": tv_weights.NFNet_F7_Weights.DEFAULT,
#     "convnext_tiny": tv_weights.ConvNeXt_Tiny_Weights.DEFAULT,
#     "convnext_small": tv_weights.ConvNeXt_Small_Weights.DEFAULT,
#     "convnext_base": tv_weights.ConvNeXt_Base_Weights.DEFAULT,
#     "convnext_large": tv_weights.ConvNeXt_Large_Weights.DEFAULT,
#     "convnext_v2_tiny": tv_weights.ConvNeXt_V2_Tiny_Weights.DEFAULT,
#     "convnext_v2_small": tv_weights.ConvNeXt_V2_Small_Weights.DEFAULT,
#     "convnext_v2_base": tv_weights.ConvNeXt_V2_Base_Weights.DEFAULT,
#     "convnext_v2_large": tv_weights.ConvNeXt_V2_Large_Weights.DEFAULT,
#     "relknet_200": tv_weights.RelKNet_200_Weights.DEFAULT,
#     "relknet_300": tv_weights.RelKNet_300_Weights.DEFAULT,
#     "relknet_400": tv_weights.RelKNet_400_Weights.DEFAULT,
#     "relknet_500": tv_weights.RelKNet_500_Weights.DEFAULT,
#     "hgnetv2_tiny": tv_weights.HGNetV2_Tiny_Weights.DEFAULT,
#     "hgnetv2_small": tv_weights.HGNetV2_SMALL_Weights.DEFAULT,
#     "hgnetv2_base": tv_weights.HGNetV2_BASE_Weights.DEFAULT,
#     "hgnetv2_large": tv_weights.HGNetV2_LARGE_Weights.DEFAULT,
#     }