"""Model catalog constants used by the benchmark loader."""

TORCHVISION_FAMILY_CATALOG = {
    "mobilenetv2": ["mobilenet_v2"],
    "mobilenetv3": ["mobilenet_v3_large", "mobilenet_v3_small"],
    "resnet": ["resnet18", "resnet34", "resnet50", "resnet101", "resnet152"],
    "resnext": ["resnext50_32x4d", "resnext101_32x8d"],
    "regnet": ["regnet_y_400mf", "regnet_y_800mf", "regnet_y_1_6gf", "regnet_y_3_2gf"],
    "resnest": ["resnest50", "resnest101", "resnest200", "resnest269"],
    "regnest": ["regnest200", "regnest269"],
    "efficientnet": [
        "efficientnet_b0",
        "efficientnet_b1",
        "efficientnet_b2",
        "efficientnet_b3",
        "efficientnet_b4",
        "efficientnet_b5",
        "efficientnet_b6",
        "efficientnet_b7",
    ],
    "efficientnetv2": ["efficientnet_v2_s", "efficientnet_v2_m", "efficientnet_v2_l"],
    "repvgg": ["repvgg_a0", "repvgg_a1", "repvgg_a2", "repvgg_b0", "repvgg_b1", "repvgg_b2", "repvgg_b3"],
    "nfnet": ["nfnet_f0", "nfnet_f1", "nfnet_f2", "nfnet_f3", "nfnet_f4", "nfnet_f5", "nfnet_f6", "nfnet_f7"],
    "convnext": ["convnext_tiny", "convnext_small", "convnext_base", "convnext_large"],
    "convnextv2": ["convnextv2_tiny", "convnextv2_small", "convnextv2_base", "convnextv2_large"],
    "relknet": ["relknet_200", "relknet_300", "relknet_400", "relknet_500"],
    "hgnetv2": ["hgnetv2_tiny", "hgnetv2_small", "hgnetv2_base", "hgnetv2_large"],
}

# (model_name, weights, transforms)
TORCHVISION_MODEL_CATALOG = {
    ("mobilenet_v2", "MobileNet_V2_Weights", "MobileNet_V2_Weights.IMAGENET1K_V1.transforms"),
    ("mobilenet_v3_small", "MobileNet_V3_Small_Weights", "MobileNet_V3_Small_Weights.IMAGENET1K_V1.transforms"),
    ("mobilenet_v3_large", "MobileNet_V3_Large_Weights", "MobileNet_V3_Large_Weights.IMAGENET1K_V1.transforms"),
    ("convnext_tiny", "ConvNeXt_Tiny_Weights", "ConvNeXt_Tiny_Weights.IMAGENET1K_V1.transforms"),
    ("convnext_small", "ConvNeXt_Small_Weights", "ConvNeXt_Small_Weights.IMAGENET1K_V1.transforms"),
    ("convnext_base", "ConvNeXt_Base_Weights", "ConvNeXt_Base_Weights.IMAGENET1K_V1.transforms"),
    ("convnext_large", "ConvNeXt_Large_Weights", "ConvNeXt_Large_Weights.IMAGENET1K_V1.transforms"),
    ("regnet_y_400mf", "RegNet_Y_400MF_Weights", "RegNet_Y_400MF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_y_800mf", "RegNet_Y_800MF_Weights", "RegNet_Y_800MF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_y_1_6gf", "RegNet_Y_1_6GF_Weights", "RegNet_Y_1_6GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_y_3_2gf", "RegNet_Y_3_2GF_Weights", "RegNet_Y_3_2GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_x_400mf", "RegNet_X_400MF_Weights", "RegNet_X_400MF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_x_800mf", "RegNet_X_800MF_Weights", "RegNet_X_800MF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_x_1_6gf", "RegNet_X_1_6GF_Weights", "RegNet_X_1_6GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_x_3_2gf", "RegNet_X_3_2GF_Weights", "RegNet_X_3_2GF_Weights.IMAGENET1K_V2.transforms"),
    ("alexnet", "AlexNet_Weights", "AlexNet_Weights.IMAGENET1K_V1.transforms"),
    ("densenet121", "DenseNet121_Weights", "DenseNet121_Weights.IMAGENET1K_V1.transforms"),
    ("densenet161", "DenseNet161_Weights", "DenseNet161_Weights.IMAGENET1K_V1.transforms"),
    ("densenet169", "DenseNet169_Weights", "DenseNet169_Weights.IMAGENET1K_V1.transforms"),
    ("densenet201", "DenseNet201_Weights", "DenseNet201_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_b0", "EfficientNet_B0_Weights", "EfficientNet_B0_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_b1", "EfficientNet_B1_Weights", "EfficientNet_B1_Weights.IMAGENET1K_V2.transforms"),
    ("efficientnet_b2", "EfficientNet_B2_Weights", "EfficientNet_B2_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_b3", "EfficientNet_B3_Weights", "EfficientNet_B3_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_b4", "EfficientNet_B4_Weights", "EfficientNet_B4_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_b5", "EfficientNet_B5_Weights", "EfficientNet_B5_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_b6", "EfficientNet_B6_Weights", "EfficientNet_B6_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_b7", "EfficientNet_B7_Weights", "EfficientNet_B7_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_v2_l", "EfficientNet_V2_L_Weights", "EfficientNet_V2_L_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_v2_m", "EfficientNet_V2_M_Weights", "EfficientNet_V2_M_Weights.IMAGENET1K_V1.transforms"),
    ("efficientnet_v2_s", "EfficientNet_V2_S_Weights", "EfficientNet_V2_S_Weights.IMAGENET1K_V1.transforms"),
    ("googlenet", "GoogLeNet_Weights", "GoogLeNet_Weights.IMAGENET1K_V1.transforms"),
    ("inception_v3", "Inception_V3_Weights", "Inception_V3_Weights.IMAGENET1K_V1.transforms"),
    ("maxvit_t", "MaxVit_T_Weights", "MaxVit_T_Weights.IMAGENET1K_V1.transforms"),
    ("mnasnet0_5", "MNASNet0_5_Weights", "MNASNet0_5_Weights.IMAGENET1K_V1.transforms"),
    ("mnasnet0_75", "MNASNet0_75_Weights", "MNASNet0_75_Weights.IMAGENET1K_V1.transforms"),
    ("mnasnet1_0", "MNASNet1_0_Weights", "MNASNet1_0_Weights.IMAGENET1K_V1.transforms"),
    ("mnasnet1_3", "MNASNet1_3_Weights", "MNASNet1_3_Weights.IMAGENET1K_V1.transforms"),
    ("regnet_x_16gf", "RegNet_X_16GF_Weights", "RegNet_X_16GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_x_32gf", "RegNet_X_32GF_Weights", "RegNet_X_32GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_x_8gf", "RegNet_X_8GF_Weights", "RegNet_X_8GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_y_128gf", "RegNet_Y_128GF_Weights", "RegNet_Y_128GF_Weights.IMAGENET1K_SWAG_E2E_V1.transforms"),
    ("regnet_y_16gf", "RegNet_Y_16GF_Weights", "RegNet_Y_16GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_y_32gf", "RegNet_Y_32GF_Weights", "RegNet_Y_32GF_Weights.IMAGENET1K_V2.transforms"),
    ("regnet_y_8gf", "RegNet_Y_8GF_Weights", "RegNet_Y_8GF_Weights.IMAGENET1K_V2.transforms"),
    ("resnet18", "ResNet18_Weights", "ResNet18_Weights.IMAGENET1K_V1.transforms"),
    ("resnet34", "ResNet34_Weights", "ResNet34_Weights.IMAGENET1K_V1.transforms"),
    ("resnet50", "ResNet50_Weights", "ResNet50_Weights.IMAGENET1K_V2.transforms"),
    ("resnet101", "ResNet101_Weights", "ResNet101_Weights.IMAGENET1K_V2.transforms"),
    ("resnet152", "ResNet152_Weights", "ResNet152_Weights.IMAGENET1K_V2.transforms"),
    ("resnext50_32x4d", "ResNeXt50_32X4D_Weights", "ResNeXt50_32X4D_Weights.IMAGENET1K_V2.transforms"),
    ("resnext101_32x8d", "ResNeXt101_32X8D_Weights", "ResNeXt101_32X8D_Weights.IMAGENET1K_V2.transforms"),
    ("resnext101_64x4d", "ResNeXt101_64X4D_Weights", "ResNeXt101_64X4D_Weights.IMAGENET1K_V1.transforms"),
    ("shufflenet_v2_x0_5", "ShuffleNet_V2_X0_5_Weights", "ShuffleNet_V2_X0_5_Weights.IMAGENET1K_V1.transforms"),
    ("shufflenet_v2_x1_0", "ShuffleNet_V2_X1_0_Weights", "ShuffleNet_V2_X1_0_Weights.IMAGENET1K_V1.transforms"),
    ("shufflenet_v2_x1_5", "ShuffleNet_V2_X1_5_Weights", "ShuffleNet_V2_X1_5_Weights.IMAGENET1K_V1.transforms"),
    ("shufflenet_v2_x2_0", "ShuffleNet_V2_X2_0_Weights", "ShuffleNet_V2_X2_0_Weights.IMAGENET1K_V1.transforms"),
    ("squeezenet1_0", "SqueezeNet1_0_Weights", "SqueezeNet1_0_Weights.IMAGENET1K_V1.transforms"),
    ("squeezenet1_1", "SqueezeNet1_1_Weights", "SqueezeNet1_1_Weights.IMAGENET1K_V1.transforms"),
    ("swin_b", "Swin_B_Weights", "Swin_B_Weights.IMAGENET1K_V1.transforms"),
    ("swin_s", "Swin_S_Weights", "Swin_S_Weights.IMAGENET1K_V1.transforms"),
    ("swin_t", "Swin_T_Weights", "Swin_T_Weights.IMAGENET1K_V1.transforms"),
    ("swin_v2_b", "Swin_V2_B_Weights", "Swin_V2_B_Weights.IMAGENET1K_V1.transforms"),
    ("swin_v2_s", "Swin_V2_S_Weights", "Swin_V2_S_Weights.IMAGENET1K_V1.transforms"),
    ("swin_v2_t", "Swin_V2_T_Weights", "Swin_V2_T_Weights.IMAGENET1K_V1.transforms"),
    ("vgg11", "VGG11_Weights", "VGG11_Weights.IMAGENET1K_V1.transforms"),
    ("vgg11_bn", "VGG11_BN_Weights", "VGG11_BN_Weights.IMAGENET1K_V1.transforms"),
    ("vgg13", "VGG13_Weights", "VGG13_Weights.IMAGENET1K_V1.transforms"),
    ("vgg13_bn", "VGG13_BN_Weights", "VGG13_BN_Weights.IMAGENET1K_V1.transforms"),
    ("vgg16", "VGG16_Weights", "VGG16_Weights.IMAGENET1K_V1.transforms"),
    ("vgg16_bn", "VGG16_BN_Weights", "VGG16_BN_Weights.IMAGENET1K_V1.transforms"),
    ("vgg19", "VGG19_Weights", "VGG19_Weights.IMAGENET1K_V1.transforms"),
    ("vgg19_bn", "VGG19_BN_Weights", "VGG19_BN_Weights.IMAGENET1K_V1.transforms"),
    ("vit_b_16", "ViT_B_16_Weights", "ViT_B_16_Weights.IMAGENET1K_V1.transforms"),
    ("vit_b_32", "ViT_B_32_Weights", "ViT_B_32_Weights.IMAGENET1K_V1.transforms"),
    ("vit_h_14", "ViT_H_14_Weights", "ViT_H_14_Weights.IMAGENET1K_SWAG_E2E_V1.transforms"),
    ("vit_l_16", "ViT_L_16_Weights", "ViT_L_16_Weights.IMAGENET1K_V1.transforms"),
    ("vit_l_32", "ViT_L_32_Weights", "ViT_L_32_Weights.IMAGENET1K_V1.transforms"),
    ("wide_resnet50_2", "Wide_ResNet50_2_Weights", "Wide_ResNet50_2_Weights.IMAGENET1K_V2.transforms"),
    ("wide_resnet101_2", "Wide_ResNet101_2_Weights", "Wide_ResNet101_2_Weights.IMAGENET1K_V2.transforms"),
}